backend:
  name: github
  repo: jenvanschmus/fouza
  branch: main
  base_url: https://fouza-cms-auth.jenvanschmus.workers.dev
  auth_endpoint: auth

media_folder: "public/site-assets/gallery"
public_folder: "/site-assets/gallery"

collections:
  - name: "gallery"
    label: "Gallery Items"
    folder: "src/content/gallery"
    create: true
    slug: "{{title}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Product Image", name: "image", widget: "image" }
      - { label: "Date Added", name: "date", widget: "datetime" }
      - { label: "Description & Details", name: "body", widget: "markdown" }
